### ISSUE TITLE
-

### ISSUE THREAD

**Issue by cuj** [acamso/demos#1]
>

**Comment by acamso** [comment]
Yeah, you can add a wordlist in a variety of ways.

You could load the wordlist from file and do something like:

`WORDS = open("wordlist.txt").read().splitlines()
`
`
PWORDS = [w + str(i) for i in range(10) for w in WORDS]
`

**Comment by cuj** [comment]
Thanks for letting me know, but I had to add `encoding='latin-1'` for rockyou.txt wordlist to work, but I ran into another issue, when running the brute forcing script, it just does nothing, just a blinking underscore, so is there a way to solve the blinking underscore issue? thanks.
